# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class GithubUserItem(scrapy.Item):
    login = scrapy.Field()
    id = scrapy.Field()
    avatar_url = scrapy.Field()
    gravatar_id = scrapy.Field()
    url = scrapy.Field()
    html_url = scrapy.Field()
    followers_url = scrapy.Field()
    following_url = scrapy.Field()
    gists_url = scrapy.Field()
    starred_url = scrapy.Field()
    subscriptions_url = scrapy.Field()
    organizations_url = scrapy.Field()
    repos_url = scrapy.Field()
    events_url = scrapy.Field()
    received_events_url = scrapy.Field()
    type = scrapy.Field()
    site_admin = scrapy.Field()
    score = scrapy.Field()


class GithubUserDetailItem(GithubUserItem):
    name = scrapy.Field()
    company = scrapy.Field()
    blog = scrapy.Field()
    location = scrapy.Field()
    email = scrapy.Field()
    hireable = scrapy.Field()
    bio = scrapy.Field()
    public_repos = scrapy.Field()
    public_gists = scrapy.Field()
    followers = scrapy.Field()
    following = scrapy.Field()
    created_at = scrapy.Field()
    updated_at = scrapy.Field()

class GithubRepoDetailItem(scrapy.Item):
    id = scrapy.Field()
    name = scrapy.Field()
    full_name = scrapy.Field()
    owner = scrapy.Field()
    owner_login = scrapy.Field()
    private = scrapy.Field()
    html_url = scrapy.Field()
    description = scrapy.Field()
    fork = scrapy.Field()
    url = scrapy.Field()
    forks_url = scrapy.Field()
    keys_url = scrapy.Field()
    collaborators_url = scrapy.Field()
    teams_url = scrapy.Field()
    hooks_url = scrapy.Field()
    issue_events_url = scrapy.Field()
    events_url = scrapy.Field()
    assignees_url = scrapy.Field()
    branches_url = scrapy.Field()
    tags_url = scrapy.Field()
    blobs_url = scrapy.Field()
    git_tags_url = scrapy.Field()
    git_refs_url = scrapy.Field()
    trees_url = scrapy.Field()
    statuses_url = scrapy.Field()
    languages_url = scrapy.Field()
    stargazers_url = scrapy.Field()
    contributors_url = scrapy.Field()
    subscribers_url = scrapy.Field()
    subscription_url = scrapy.Field()
    commits_url = scrapy.Field()
    git_commits_url = scrapy.Field()
    comments_url = scrapy.Field()
    issue_comment_url = scrapy.Field()
    contents_url = scrapy.Field()
    compare_url = scrapy.Field()
    merges_url = scrapy.Field()
    archive_url = scrapy.Field()
    downloads_url = scrapy.Field()
    issues_url = scrapy.Field()
    pulls_url = scrapy.Field()
    milestones_url = scrapy.Field()
    notifications_url = scrapy.Field()
    labels_url = scrapy.Field()
    releases_url = scrapy.Field()
    deployments_url = scrapy.Field()
    created_at = scrapy.Field()
    updated_at = scrapy.Field()
    pushed_at = scrapy.Field()
    git_url = scrapy.Field()
    ssh_url = scrapy.Field()
    clone_url = scrapy.Field()
    svn_url = scrapy.Field()
    homepage = scrapy.Field()
    size = scrapy.Field()
    stargazers_count = scrapy.Field()
    watchers_count = scrapy.Field()
    language = scrapy.Field()
    has_issues = scrapy.Field()
    has_downloads = scrapy.Field()
    has_wiki = scrapy.Field()
    has_pages = scrapy.Field()
    forks_count = scrapy.Field()
    mirror_url = scrapy.Field()
    open_issues_count = scrapy.Field()
    forks = scrapy.Field()
    open_issues = scrapy.Field()
    watchers = scrapy.Field()
    default_branch = scrapy.Field()
