-- name: create-table-user
-- Github users
CREATE TABLE IF NOT EXISTS user (
    id integer primary key,
    login text NULL,
    avatar_url text NULL,
    gravatar_id text NULL,
    url text NULL,
    html_url text NULL,
    followers_url text NULL,
    following_url text NULL,
    gists_url text NULL,
    starred_url text NULL,
    subscriptions_url text NULL,
    organizations_url text NULL,
    repos_url text NULL,
    events_url text NULL,
    received_events_url text NULL,
    type text NULL,
    site_admin text NULL,
    name text NULL,
    company text NULL,
    blog text NULL,
    location text NULL,
    email text NULL,
    hireable text NULL,
    bio text NULL,
    public_repos text NULL,
    public_gists text NULL,
    followers integer NULL,
    following integer NULL,
    created_at timestamp NULL,
    updated_at timestamp NULL,
    first_seen timestamp DEFAULT current_timestamp
);

-- name: create-table-repo
-- Github repo
CREATE TABLE IF NOT EXISTS repo (
    id integer primary key,
    name text NULL,
    full_name text NULL,
    owner integer REFERENCES user ON DELETE CASCADE ON UPDATE CASCADE,
    private boolean NULL,
    html_url text NULL,
    description text NULL,
    fork boolean NULL,
    url text NULL,
    forks_url text NULL,
    keys_url NULL,
    collaborators_url text NULL,
    teams_url text NULL,
    hooks_url text NULL,
    issue_events_url text NULL,
    events_url text NULL,
    assignees_url text NULL,
    branches_url text NULL,
    tags_url text NULL,
    blobs_url text NULL,
    git_tags_url text NULL,
    git_refs_url text NULL,
    trees_url text NULL,
    statuses_url text NULL,
    languages_url text NULL,
    stargazers_url text NULL,
    contributors_url text NULL,
    subscribers_url text NULL,
    subscription_url text NULL,
    commits_url text NULL,
    git_commits_url text NULL,
    comments_url text NULL,
    issue_comment_url text NULL,
    contents_url text NULL,
    compare_url text NULL,
    merges_url text NULL,
    archive_url text NULL,
    downloads_url text NULL,
    issues_url text NULL,
    pulls_url text NULL,
    milestones_url text NULL,
    notifications_url text NULL,
    labels_url text NULL,
    releases_url text NULL,
    deployments_url text NULL,
    created_at timestamp NULL,
    updated_at timestamp NULL,
    pushed_at timestamp NULL,
    git_url text NULL,
    ssh_url text NULL,
    clone_url text NULL,
    svn_url text NULL,
    homepage text NULL,
    size integer NULL,
    stargazers_count integer NULL,
    watchers_count integer NULL,
    language text NULL,
    has_issues boolean NULL,
    has_downloads boolean NULL,
    has_wiki boolean NULL,
    has_pages boolean NULL,
    forks_count boolean NULL,
    mirror_url text NULL,
    open_issues_count integer NULL,
    forks integer NULL,
    open_issues integer NULL,
    watchers integer NULL,
    default_branch text NULL,
    first_seen timestamp DEFAULT current_timestamp
);
